title: Resume
description: >- # this means to ignore newlines until "baseurl:"
  ""

baseurl: "/resume"
url: "https://gatecomputerscience.com"

twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed